//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BALNDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactDetail
    {
        public int CntactDetailId { get; set; }
        public string ContactDetailAddress { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ContactAddress { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
