//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BALNDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactPerson
    {
        public int ContactPersonId { get; set; }
        public string ContactName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string ContactPersonDepartment { get; set; }
        public string contactNumber { get; set; }
        public string ContactEmail { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> OrderNumber { get; set; }
    }
}
