//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BALNDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsEvent
    {
        public int NewsEventId { get; set; }
        public string NewsEventDetail { get; set; }
        public Nullable<System.DateTime> NewsEventDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> ShowOnDashBoard { get; set; }
        public string NewsEventTitle { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string NewsEventCategory { get; set; }
    }
}
