//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKarachiNimco.Forms {
    
    
    public partial class Home {
        
        /// <summary>
        /// ucHomeSliderView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebKarachiNimco.Forms.UserControl.ucHomeSliderView ucHomeSliderView;
        
        /// <summary>
        /// ucNewsAndEventDashBoard control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebKarachiNimco.Forms.UserControl.ucNewsAndEventDashBoard ucNewsAndEventDashBoard;
        
        /// <summary>
        /// ucProductDashBoard control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WebKarachiNimco.Forms.UserControl.ucProductDashBoard ucProductDashBoard;
    }
}
